import type { Metadata } from "next";
import "./globals.css";
// importしたパッケージのスタイルをimportします
import "@mantine/core/styles.css";

// @mantine/hooks以外のすべてのパッケージではスタイルのimportが必要
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
  title: "My Mantine app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // htmlタグにsuppressHydrationWarning属性を追加する。
    <html lang="ja" suppressHydrationWarning>
      <head>
        {/* headタグにColorSchemeScriptを追加する */}
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body className="antialiased">
        {/* childrenをMantineProviderでラップする */}
        <MantineProvider defaultColorScheme="auto">{children}</MantineProvider>
      </body>
    </html>
  );
}
